### ISSUE TITLE
Drop support for v2 onion services

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1112]
I wonder if we should drop support for v2 onion services altogether. They're not as secure as v3 onion services, and Tor Browser has supported v3 for a long time now. This could simplify the onion logic of OnionShare a lot, and remove the pycryptodome dependency (it's only used to detect if a key is v2 or v3).

The only benefit that v2 has is that the addresses are shorter, so they're easier to manually type.

**Comment by mig5** [comment]
Right now, Client Auth (Stealth Mode) is only possible with v2 onions. Should we wait til we add that feature for v3 onions before we do this?

There is some argument that Client Auth is less useful on v3 onions given the descriptors aren't 'discoverable' like v2 ones are. Could we let go of that functionality altogether too. However, it's maybe still useful as an additional security layer in case a descriptor is accidentally leaked.,

**Comment by micahflee** [comment]
With Tor officially beginning the deprecation process for v2 onion services, I think it's time we implement this https://kushaldas.in/posts/onion-service-v2-deprecation-timeline.html

**Comment by micahflee** [comment]
Also, client auth has much better v3 support now too. Tor Browser has a UI for it, even.

**Comment by SaptakS** [comment]
I agree. Given the deprecation and the eventual drop in supporting of v2 in 2021, it's a good idea to start dropping/deprecating v2

**Comment by holantonela** [comment]
Hi folks! as always, let us know if you have any feedback on your dev implementation side. Happy to answer any tech question as well o/

**Comment by mig5** [comment]
> Also, client auth has much better v3 support now too. Tor Browser has a UI for it, even.

I mentioned this last week in https://github.com/micahflee/onionshare/issues/697

My concern is that I can't see that Stem has any support for adding Client Auth to a v3 *ephemeral* onion.

Until that happens, I can't see that we can do anything else here that we haven't already done (marked v2 onions as 'legacy' and hid the option under 'Advanced')...

**Comment by Baccount** [comment]
Here is TorProject official deprecation plan by: David Goulet


1) September 15th, 2020
     0.4.4.x: Tor will start warning onion service operators and clients that
              v2 is deprecated and will be obsolete in version 0.4.6

  2) July 15th, 2021
     0.4.6.x: Tor will no longer support v2 and will be removed from the code
              base.

  3) October 15th, 2021
     We will release new stable versions for all supported series that will
     disable v2.

This effectively means that from _today_ (June 11th 2020), the Internet has
around 15 months to migrate from v2 to v3 once and for all.

https://lists.torproject.org/pipermail/tor-dev/2020-June/014365.html

**Comment by micahflee** [comment]
@mig5 given what you discovered in https://github.com/micahflee/onionshare/issues/697#issuecomment-645279137 that ephemeral onion services just don't support client auth yet, what do you think about holding off on deprecating v2 onion services until they do? This way we can deprecate v2 onion services at the same time as adding v3 client auth.

If we decide to do this, I can just remove the 2.3 milestone from this issue.

**Comment by mig5** [comment]
@micahflee I definitely think we should block on this unless you felt that the current use of HTTP auth is a reasonable middle ground pending 'real' Client Auth (it probably isn't, as there's likely valid use cases for separate 'auth' per user, rather than a shared user/pass like HTTP auth)
