### ISSUE TITLE
OnionShare Does not send 98.5GB file

### ISSUE THREAD

**Issue by ekstein** [onionshare/onionshare#1114]
I am trying to share a 98.5 GB file on OnionShare on a mac. I am running an Express VPN which I subscribed to. I downloaded OnionShare as well as Tor Browser. 

When I share my file it starts compressing but never gets beyond 2%. I'll check in and it will be back to 0% or 1% or 2% but never higher. Something is wrong. It says it is connected to Tor Browser

**Comment by matt1tk** [comment]
Splitting it into 25GB parts may help. Tor is definitely not built for such large files though

**Comment by mig5** [comment]
Make sure you have enough disk space on your machine. OnionShare makes a copy of your files in a temp area for sharing, it doesn't share the literal original file. The file(s) that are shared are compressed, but depending on the file type, it could still take up a lot of space. 

This may not be your issue but it is something else to check.

**Comment by leo-lb** [comment]
@mig5 @matt1tk 

Instead, OnionShare should issue a read lock then read from the original file without meaninglessly copying and compress on-the-fly as the remote user downloads. Also, with good circuits Tor is able to reach very high speed, what's more of a problem is latency, and both are linked if there's packet loss yes, but it's possible to have high latency and little packet loss, and with some luck, you can get 5 Megabytes/s over Tor as I could get at times.

**Comment by strasharo** [comment]
Is there a way to redirect it to write to a place different than /tmp? I'm trying to share 20G, but my /tmp is 16G and it's crashing.

**Comment by DevenBL** [comment]
im telling you right now you wont be able to send it even if you redirect
it or increase the temp folder size by adding swap and then re allocating
tmp with enough space.
The webserver crashes when the other party tries to download it. i later
made a 120gig tmp directory and had it compress and process properly and
host but as soon as the download starts it crashes the hosting webserver

**Comment by strasharo** [comment]
@DevenBL : Found a workaround - using the cli instead and it works fine. It appears that the glitch is in the UI version for me.
