### ISSUE TITLE
Snap permissions cause error 500

### ISSUE THREAD

**Issue by efialtos** [onionshare/onionshare#1308]
Error 500 occurs when I drag-n-drop a file or a directory into fileshare or webserver filelist, and at least one of the files or directories is placed outside the snap permissions or contains a softlink pointing to anywhere outside it.

> root# snap interfaces onionshare
> Slot                             Plug
> gnome-3-34-1804:gnome-3-34-1804  onionshare
> gtk-common-themes:gtk-3-themes   onionshare
> gtk-common-themes:icon-themes    onionshare
> gtk-common-themes:sound-themes   onionshare
> :desktop                         onionshare
> :desktop-legacy                  onionshare
> :gsettings                       onionshare
> :home                            onionshare
> :network                         onionshare
> :network-bind                    onionshare
> :opengl                          onionshare
> :wayland                         onionshare
> :x11                             onionshare

Thus the only user-available fileshare or website must be inside /home. Frustrating, isn't it?

If instead of dragging I use the button 'Add', and browse the folders, it doesn't access the folders content except /home showing them empty. Anyway it allows to choose any folder in the disk root, resulting error 500 again.

**Comment by mig5** [comment]
I get 'Is not a readable file' when I drag things from `/usr/share` that can't be read by the user running the snap . And via the 'Add' button, I simply can't see the files that I can't read, to even choose them. Which is all as per design.

In short I can't seem to reproduce this. Running OnionShare 2.3.1 on a Debian 10 Qubes VM:

```
user@disp6641:~$ snap --version
snap    2.49.2
snapd   2.49.2
series  16
debian  10
kernel  5.4.98-1.fc25.qubes.x86_64
```
