### ISSUE TITLE
Permission denied in Snap version PermissionError: [Errno 13]

### ISSUE THREAD

**Issue by AnonymousDark** [onionshare/onionshare#1320]
PermissionError: [Errno 13] Permission denied: '/etc/httpd/conf/mime.types'
when trying to use the snap version
#snap --version                                                                                                                                       ✔ 
snap     2.49.1-1
snapd    2.49.1-1
series   16
manjaro  -
kernel   5.11.6-1-MANJARO

Connections
Slot                             Plug
gnome-3-34-1804:gnome-3-34-1804  onionshare
gtk-common-themes:gtk-3-themes   onionshare
gtk-common-themes:icon-themes    onionshare
gtk-common-themes:sound-themes   onionshare
:desktop                         onionshare
:desktop-legacy                  onionshare
:gsettings                       onionshare
:home                            onionshare
:network                         onionshare
:network-bind                    onionshare
:opengl                          onionshare
:removable-media                 onionshare
:wayland                         onionshare
:x11                             onionshare

**Comment by micahflee** [comment]
What operating system are you using, and can you say steps to reproduce? When I `snap install onionshare` from Ubuntu 20.10, everything seems to work for me.

**Comment by AnonymousDark** [comment]
im using Manjaro 21 and to reproduce the issue just install and try to open nothing else error comes from fresh snap install

**Comment by mig5** [comment]
Snap package works fine for me on Debian 10 using apt-installed snap 2.37.2
