### ISSUE TITLE
Keep getting download failed

### ISSUE THREAD

**Issue by alex11star** [onionshare/onionshare#1331]
Hi, using Orbot for Android, I scan the QR code in Onionshare, go to the website, and I keep getting download failed, with and without "stop sharing after files have been sent" - any ideas?

**Comment by mig5** [comment]
Hi @alex11star ,

It's a bit tricky to diagnose without more info. Are you able to visit that same OnionShare URL in Tor Browser on a regular computer, and reproduce the same 'Download failed'? This might help us identify if it's 'our bug' or Orbot's.

I assume the actual OnionShare site itself loads in Orbot, and it's just the 'Download' action that fails?

Thanks!

**Comment by tonypachino** [comment]
i have a same problem on android, i can't download it with a tor browser i keep getting Download failed.

Where is the problem?
