### ISSUE TITLE
Add dark mode/light mode setting

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1382]
Right now it automatically detects if dark mode is enabled in the OS and if so uses it. But in some operating systems it doesn't detect this accurately. We should add a setting to allow the user to explicitly chose. The options can be Automatic, Light, or Dark, and it defaults to Automatic.

**Comment by siddhantdixit** [comment]
Sir, I would like to work on this issue! Can u assign me?

**Comment by siddhantdixit** [comment]
![image](https://user-images.githubusercontent.com/22856752/124632389-e9e2fc00-dea1-11eb-8bfc-c568461cd62b.png)

I have added separate option to choose theme in onionshare desktop.

**Comment by SaptakS** [comment]
@siddhantdixit sure! Go ahead. As options for the theme, I will recommend there be 3 different options: light, dark and system. We already have it in a way that it works (in a bit flaky way) for the system option. So basically the implementation for system is there (where it uses a not so full proof way of detecting system color mode). And light and dark options should just ignore that detection and set it to either light or dark. Let me know if you need any assistance.

**Comment by siddhantdixit** [comment]
Yeah! The default option doesn't work properly. I have enabled dark mode in Windows 10, program was not detecting "dark" mode.
We can add the theme options separately for System, Light and Dark. 

For the dark mode detection I have tested darkdetect on windows and linux it is working fine we can implement this for dark theme detection.
https://github.com/albertosottile/darkdetect

Thank you!

**Comment by micahflee** [comment]
Fixed in #1386 1386
