### ISSUE TITLE
Missing flatpak versions for 2.3.2 (and 2.3.1)

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [onionshare/onionshare#1388]
concerns https://onionshare.org/dist/
the latest version available is 2.3 instead of 2.3.2.

**Comment by mig5** [comment]
Indeed, there aren't any flatpak files in https://onionshare.org/dist/2.3.2/ or https://onionshare.org/dist/2.3.1/ , did we make those but just forget to upload them @micahflee ?

**Comment by mig5** [comment]
I think this is somewhat obsolete now, we have flatpak for newer versions, including the 2.6 released today, and we also know that older versions of OnionShare with Flatpak had bugs that made them not work at all.

Please try the latest flatpak release at https://onionshare.org/dist/2.6/OnionShare-2.6.flatpak
