### ISSUE TITLE
Light mode isn't very light on macOS 10.15.7 that uses dark mode generally

### ISSUE THREAD

**Issue by mig5** [onionshare/onionshare#1401]
I love the 'dark' mode in OnionShare 2.3.2:

<img width="1038" alt="onionshare-dark" src="https://user-images.githubusercontent.com/99173/130375632-53f0bd7e-07fe-4705-afc8-fadb012264a8.png">

But I tried switching to 'light' mode and was surprised to find that it wasn't really all that light:

<img width="1038" alt="onionshare-light" src="https://user-images.githubusercontent.com/99173/130375643-81c4386e-fd99-46d9-89b2-b08dec7891f4.png">

Some bits are 'light' but it's actually hard to read. I'm not sure if it's because the rest of my Mac is in 'dark' mode but I thought the recent changes for theme 'selection' meant it would really be forced regardless of the OS' general light/dark settings? Or have I misunderstood that?

**Comment by SaptakS** [comment]
It seems like that's the case, though I feel like I tested this. Maybe I just tested the opposite case. Will fix this.
