### ISSUE TITLE
OnionShare 2.3.2 worked fine, upgraded to 2.3.3 and now repeatedly states cannot connect to Tor

### ISSUE THREAD

**Issue by ASmith-** [onionshare/onionshare#1403]
OnionShare 2.2 worked fine, upgraded to 2.3.3 via flatpak and now quits after 15 seconds without error messages.

Previously,
Error Message after creating a 100% Tor Network Circuit and selecting 'Save'

OnionShare could not connect to Tor: Errno 2] No such file or directory.

I've gone through nearly all the possible Onionshare tor connection options, many appear to successfully create a Tor Network connection via bridges, direct, browser. None apparently however can be saved and therefore I'm unable to use OnionShare at its present condition. 

Perhaps the developer or another user can shed some light on the error message, 'No such file or directory', I'm running multiple instances of the onion network on this workstation, Linux Mint 20.1 without any issues at all. I recently built the newest Tor 0.4.6.7 stable from the source code and also installed that to the system files. 

Connected to the Tor controller.

Tor version: 0.4.6.7
Supports ephemeral onion services: True.
Supports client authentication: False.
Supports next-gen .onion addresses: True.

Unable to Save the configuration, hence unable to use Onionshare 2.3.2
If the 'Save' button is selected then

OnionShare could not connect to Tor:
[Errno 2] No such file or directory

Try changing how OnionShare connects to the Tor network in the settings. (Which as I have explained, I have tried nearly all of the possible ways OnionShare could connect to the Tor network in the settings. Some work, afew (Control, Socket methods) do not. However none even after successfully creating a Tor Network circuit 100% are able to be 'Saved'.

Update on this failure to connect issue
I found the Onionshare 2.2 had been installed via a .deb file which I prefer for small utility files rather than the much larger installers like snap and perhaps even flatpak. 

When I installed Onionshare 2.3.3 via flatpak I had both Onionshare applications briefly on my file system. I uninstalled the Onionshare v2.2 leaving only the newest Onionshare 2.3.3 installed by the flatpak. However when I attempt to open and run that application on this linux mint desktop, there are no error messages, nothing, it appears the system is trying to run Onionshare 2.3.3 but quits after about 15 seconds. 

The Linux Mint distro installed Onionshare at /usr/bin/onionshare-gui  , I don't know where flatpak placed it previously or I could have tried to run the updated application in a terminal window for more clues as to why it's failing to even run.

**Comment by micahflee** [comment]
Try deleting `~/.config/onionshare` and then re-launching it. It's possible something in your settings is corrupted and preventing it from starting.

**Comment by mig5** [comment]
Closing in favour of #1374 regarding the lock file issue.
