### ISSUE TITLE
Update v3 client auth UX

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1409]
@glenn-sorrentino did some work on improving the v3 client auth UX.

![Active + Activity Panel](https://user-images.githubusercontent.com/156128/131383807-b528c2db-6080-4c95-88ed-d2bbc016b779.png)

I think we might want to change the wording a bit still, but I like the idea of splitting the address/private key into two numbered steps, and having separate QR code buttons that just show one QR code at a time.

Maybe, if public mode is disabled, it can say:

> 1. **Anyone** with this OnionShare address and private key can **(download, upload, chat, etc.)** using the **Tor Browser**
> `http://shgjd4amgl2xwa2fdmw4zztkwzuk3tsqhkolu6sn4mipv6iatq3xuaad.onion`
> [Copy Address] [Show QR Code]
> 
> 2. They will need to enter this **private key** to access your OnionShare service
> [Copy Private Key] [Show QR Code]

If public mode is enabled:

> **Anyone** with this OnionShare address can **(download, upload, chat, etc.)** using the **Tor Browser**
> `http://shgjd4amgl2xwa2fdmw4zztkwzuk3tsqhkolu6sn4mipv6iatq3xuaad.onion`
> [Copy Address] [Show QR Code]

**Comment by glenn-sorrentino** [comment]
Wonder if the "Anyone..." line should actually be above the numbered lst? 

**Anyone** with this OnionShare address and private key can (**download, upload, chat, etc.**) using the **Tor Browser**.
1. First, send the OnionShare address below:
> ` http://shgjd4amgl2xwa2fdmw4zztkwzuk3tsqhkolu6sn4mipv6iatq3xuaad.onion`
[Copy Address] [Show QR Code]

2. Next, send this **private key** to allow access to your OnionShare service.
[Copy Keu] [Show QR Code]

**Comment by micahflee** [comment]
I like it.

**Comment by mig5** [comment]
Thanks @glenn-sorrentino! I'll get to work on this today!
