### ISSUE TITLE
Application UI hangs

### ISSUE THREAD

**Issue by mmhy2003** [onionshare/onionshare#1419]
I really love your application and its simple UI experience.
But I am really annoyed from GUI hanging whenever something is getting processed in the background.
Like for example on the settings page, when I try to test the Tor connection, the interface totally freezes.

I recommend separating UI & BG processing in different threads to avoid application interface freezing.

Peace.

**Comment by micahflee** [comment]
I think testing Tor settings is the only place where it doesn't happen in a background thread. Did you see any other places where the UI hangs? Putting that in a background thread is a good idea though.

**Comment by mig5** [comment]
I think this is now fixed (in develop branch). In the new TorSettings Tab, the 'Test settings' option, along with the Tor reconnection when saving settings, runs in a TorConnectionThread, and it's possible to navigate around to other tabs whilst this takes place - no hanging.
