### ISSUE TITLE
Automatic detection of user location

### ISSUE THREAD

**Issue by SaptakS** [onionshare/onionshare#1422]
When trying out a bridge, if user opts in for automatic detection of location, we should use this logic for detecting user's location. If the automatic location can't be determined, show the option to select location manually. I think @mig5 can better describe the exact implementation for this.

**Comment by mig5** [comment]
> I think @mig5 can better describe the exact implementation for this.

As far as I understand it, the Tor Project intend to provide and manage an API endpoint that will do a geoip lookup based on the user's IP address (probably from the X-Forwarded-For header), and return a country code in the response.

See this comment https://gitlab.torproject.org/tpo/anti-censorship/bridgedb/-/issues/40025#note_2748906

> So currently we are wanting 3 APIs (NOTE edited to match latest discussion):

```
 /* Get Cirucmvention Settings
   
   return a JSON array of TorSettings objects in the following format based on the detected location
   of the query (using X-Forwarded-For HTTP header?). We return an Array of these objects to provide
   end-users with alternatives (sorted by order in which we would prefer users to use them, with the
   most preferred configuration appearing first, least preferred last)
```

Presumably, this API, like the censorship map in #1423 (which per the same link above, is another API endpoint on the Tor Project-managed service), will be reachable using 'domain fronting' techniques, to try to evade the censor blocking the request to the Tor Project API itself.

As I understand it, this means we'll be able to domain-front hit this API and get the country code back. We won't have to run any geo-ip stuff in OnionShare itself.

We'll just need a method that:

1) requests a hit to that API after the user opts in to try to automatically solve any connection issue.

2) Once we have the country code, hit the other API endpoint to get a list of ideal bridge options for that country (#1364) 

3) Then attempt to auto-configure bridges using the bridge technology recommended in the response to 2)

The Gitlab story above, though, also says:

> Our original design was two API calls, first to find geolocation and then second to request settings for a country-code. Later we figured there was not much point, since BridgeDB can figure out the caller's location through the X-Forwarded-For header, so we reduced it to a single request. 

That is not what it looks like in the API spec in the same ticket - it still looks like a separate request to get a country code, and a separate request to get settings for that country.

## Other thoughts

Anything in a Tor-based app that tries to learn the user's location strikes me as really risky.

I really think that the nature of Tor-based apps means that there'll be a number of users who might really be troubled that the app is going to go and find their location based on their *real* IP. A vast majority of users will probably prefer the convenience of the new flow, but some will consider it really bad, or even a sinister change. I imagine the Tor Project are anticipating the same thing in terms of blowback..

We should be mindful of that, and in our UX, try to use clear language to explain what the 'Quickstart' feature will do, *if* the native Tor connection didn't work (most of the time it probably will, so the location/country stuff won't even need to be a step for those users), including that OnionShare will briefly try to find good settings for the user's location in the safest - but not-yet-Tor-connected way - possible.

## Where to from here

Ultimately, I feel like most of the OnionShare side of things is blocked until that API sees the light of day on the TorProject side. We can't do much til it exists, and it blocks things like working out how to request bridges etc (whether captchas will somehow be involved/exposed to the user to complete, etc).

**Comment by SaptakS** [comment]
> We should be mindful of that, and in our UX, try to use clear language to explain what the 'Quickstart' feature will do

Yes, clear language and providing user options at every step to do manual configuration as well I think is key to make users confident and opt-in to the automatic thing only if they are comfortable, else have plenty of option to do their own settings and never actually needing to make a not-very-Tor-connection, I guess

**Comment by micahflee** [comment]
Here is roughly what I'm thinking for the UI.

If Tor fails to connect:

> Failed connecting to Tor. This could be because your internet is being censored. You might be able to get around this censorship by using a Tor bridge.
> 
> [x] Automatically determine my location to bypass country-specific censorship
> [ ] Manually select your country
> 
> [world map]
> 
> [Use a Tor Bridge] [Tor Settings]

If you click on a country on the world map, it switches to "Manually select your country" and highlights the country you clicked. If you select "Automatically determine" it unselects the country on the world map.

When the user clicks "Use a Tor Bridge", all fields are disabled. If "Automatically determine my location" is checked, it updates the world map once it is determined. Then it requests bridges from censorship API, and tries connecting to Tor.

**Comment by micahflee** [comment]
Here is a useful repo full of lists of all the countries, including in different languages: https://github.com/umpirsky/country-list

**Comment by mig5** [comment]
Meskio confirmed that if the Tor API fails to determine the user's country code based on their IP, there will be a esponse with this json blob:

```
{
  "errors": [
    {
      "code": 406,
      "detail": "Could not find country code for circumvention settings"
    }
  ]
}
```

If we spot this 406 code, we should raise the option for the user to choose their country.

Note that regardless of error codes and details, Tor's API *HTTP* response is always 200 (for 'historical' reasons, apparently...)
