### ISSUE TITLE
Apply country specific bridge rules

### ISSUE THREAD

**Issue by SaptakS** [onionshare/onionshare#1423]
Based on the country determined either by automatic detection or location selection, apply the rules from the censorship map that matches with the country. Then try to connect again over tor.

There seems to be some discussion around making the censorship map available over a domain-fronted URL: https://gitlab.torproject.org/tpo/anti-censorship/bridgedb/-/issues/40025

Censorship map: https://gitlab.torproject.org/tpo/anti-censorship/state-of-censorship/-/blob/main/state-of-censorship.json

**Comment by mig5** [comment]
Meskio confirmed upstream that the response to the 'get me bridges' route can sometimes be an empty `{}`, for cases where a country has no known censorship and so no recommendations. But it could also occur if there is some problem at the Tor API.

> Take into account that even if we don't have any circumvention settings for your country that doesn't mean you don't need any, you might be in a network that blocks access to tor (my local uni does) or our circumvention settigns might be wrong. Will OnionShare ask the user for manual settings and/or recommend default bridges if got a {} from the settings?

We will already be in a situation where Tor has failed to connect and hence having tried this route in the first place. We will also deal separately with the situation whereby the user's country code has failed to be detected (https://github.com/onionshare/onionshare/issues/1422#issuecomment-987251251).

So if we still get `{}` after all this, I think we should give up, and take the user to the TorSettingsTab to manually configure bridges or try another Tor connection method.
