### ISSUE TITLE
Support snowflake bridges, and update bridge selection UI

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1442]
We need to add support for snowflake bridge (source code [here](https://gitweb.torproject.org/pluggable-transports/snowflake.git)), and we should also update our UI to look like Tor Browser's UI:

![Screenshot from 2021-10-11 19-47-17](https://user-images.githubusercontent.com/156128/136882759-7080158b-8e81-43ca-875b-e222d0c7b19c.png)
![Screenshot from 2021-10-11 19-47-42](https://user-images.githubusercontent.com/156128/136882760-49d21868-0a44-47a5-b3bd-50d575fa0776.png)

While not necessary, if it turns out to not be too much work it would be cool to support "Request a bridge from torproject.org" as well:

![Screenshot from 2021-10-11 19-47-56](https://user-images.githubusercontent.com/156128/136882762-5129d479-ee2c-4874-8d70-0ddbff373fbd.png)
![Screenshot from 2021-10-11 19-48-10](https://user-images.githubusercontent.com/156128/136882766-b616109c-2a03-4eb3-b6c8-fbe14f351e8b.png)

Right now during development in Linux we tell users to install `tor` and `obfs4proxy` from their package manager, but `snowflake` isn't widely packaged. So this issue will involve making a `get-tor-linux.py` that downloads the linux Tor Browser and extracts binaries, including `snowflake-client` (which is in `tor-browser_en-US/Browser/TorBrowser/Tor/PluggableTransports/snowflake-client`), for development. And then we'll build snowflake from source for Flatpak and Snapcraft.

**Comment by micahflee** [comment]
I moved the packaging stuff to #1459 so that PR $1449 can finally close this issue.

**Comment by mig5** [comment]
I think we can close this one out since #1449 was merged! #1459 contains the remaining packaging steps.
