### ISSUE TITLE
onionshare 2 onionshare ?

### ISSUE THREAD

**Issue by ihubgit** [onionshare/onionshare#1456]
Hi, is there a reason file transfers can't be done between two instances of the onionshare app, bypassing Torbrowser ?
That would be easier for the end user : the same app can both send and receive files...

**Comment by mig5** [comment]
There are some reasons - the main one is that it dramatically increases the code quantity, and therefore the attack surface of OnionShare. 

There are a great many potential vulnerabilities to do with fetching a share from an OnionShare service, that we are able to automatically avoid thanks to all the hard work that has gone into Tor Browser to mitigate them already.

But, it's not impossible, and there are good reasons to do it (one of them relates to opportunities we have to 'speed up' a download), and so it might happen in the future.

We actually have an issue for it already - https://github.com/onionshare/onionshare/issues/365 - so I'll close this as a duplicate. Thanks!
