### ISSUE TITLE
onion-share crashes when open on macOs 10.12

### ISSUE THREAD

**Issue by sam-smart-byte** [onionshare/onionshare#1468]
I installed onion share via brew on mac, it installed successfully but when open it crashes.
I add the report below

[onion-share-crash-sam.txt](https://github.com/onionshare/onionshare/files/7533704/onion-share-crash-sam.txt)

bye!
(v 2.4)

**Comment by mig5** [comment]
With MacOS 10.12 (Sierra) having reached end-of-life in 2019, I am not sure we can allocate resources to look at solving this, unfortunately. Sorry.

https://computing.cs.cmu.edu/news/2019/eol-macos-sierra
