### ISSUE TITLE
onionshare 2.4 start receiving files never succeeds

### ISSUE THREAD

**Issue by ihubgit** [onionshare/onionshare#1472]
Hi, installed 2.4 on windows 10.
Successfully connected to the Tor network without bridges, but when choosing receive files option, I'm getting 
_Starting... Click to cancel_ but only getting the yellow dot _Starting..._ and it never succeeds.
I'm on a mobile wifi router.
Funny enough, sending works (albeit very slow speeds though : hovering around 30 kb/s)!

**Comment by mig5** [comment]
I'm afraid this is likely to be just a Tor connection issue at your end, not a bug or an OnionShare problem. If a connection to Tor isn't able to be made, OnionShare can't be used. 

The difference betwen sending vs receiving is going to just be down to (bad) luck - there's no difference in the Tor connection method.

You could look at using Bridges to connect to Tor (configurable in the settings) which might improve your chances of making a successful connection - or using the 'Attempt auto-configuration with Tor Browser' option.

Good luck!
