### ISSUE TITLE
"Connecting to the Tor network" is frozen

### ISSUE THREAD

**Issue by EelOnMusk** [onionshare/onionshare#1477]
Hey OnionShare. I've tried to host a website using your service, but I can't connect to the Tor network. If I try and configure it manually, no option seems to help. After re-installing it several times, nothing has changed. Please let me know what I can do.

![frozen](https://user-images.githubusercontent.com/94814303/142791645-79296701-4467-4657-8e81-cb9166ba3298.png)

**Comment by mig5** [comment]
What happens when you start Tor Browser, and then configure the OnionShare settings to 'Attempt auto-configuration with Tor Browser'?

Does using the Tor Browser itself work for browsing the internet or onion addresses?

**Comment by EelOnMusk** [comment]
The loading function freezes at 0% when I try to connect through the inbuilt Tor on onionshare. Tor browser works perfectly fine though. I can view all v3 onion addresses. I ended up just hosting my site on onionshare by connecting through tor. I'm not to sure what's happening, but I'm still happy to donate.
Cheers, EEL ON MUSK.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mig5** [comment]
I think ultimately your computer/network had an issue connecting to Tor which could not be resolved by OnionShare itself. 

The next release of OnionShare (2.6) should do better at detecting network issues and offering you the ability to automatically try a 'bridge' to resolve issues connecting to Tor. Please try it once it's released, if you get a chance, and let us know if it works for you.
