### ISSUE TITLE
Does not work in Apple Silicon M1 computers

### ISSUE THREAD

**Issue by osvik** [onionshare/onionshare#1481]
It does not work in Apple Silicon M1 computers `AArch64`. Native or trough Rosetta 2.

Error:

<img width="794" alt="Screenshot 2021-11-29 at 22 12 59" src="https://user-images.githubusercontent.com/678916/143943870-80020313-dece-4227-8e53-465eb6b89e42.png">

Tested in Mac OS 12.0.1 Monterey.

**Comment by mig5** [comment]
#1414
