### ISSUE TITLE
Check for updates after connecting to Tor

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1487]
In the major refactor with the quickstart screen, we lost the bit of logic that checks for available OnionShare updates in Windows and macOS after connecting to Tor. From version 2.4:

https://github.com/onionshare/onionshare/blob/d08d5f0f32f755f504494d80794886f346fbafdb/desktop/src/onionshare/main_window.py#L145-L154

We should make sure after successfully connecting to Tor in the quickstart screen, we check for updates.

**Comment by mig5** [comment]
I've pushed a fix for this into https://github.com/onionshare/onionshare/pull/1488

https://github.com/onionshare/onionshare/pull/1488/commits/1fd43b316b7560b77676d7fbed52ec8f46fed518
