### ISSUE TITLE
Stop referring to Client Authentication / Client Authorization as 'Stealth'?

### ISSUE THREAD

**Issue by mig5** [onionshare/onionshare#1499]
We had a comment at https://hosted.weblate.org/translate/onionshare/translations/en/?&offset=97#comments asking what 'Stealth' means.

I think we are the only project that still refers to Client Authentication as 'Stealth'. I think we should probably just use 'Client Authentication' - in fact, Tor calls it Client *Authorization*: https://community.torproject.org/onion-services/advanced/client-auth/ . Do we want to use Client Authorization everywhere? My only personal pedantic distaste for 'Authorization' is that the z is American spelling (I would use 's'), but we don't have a difference between American and British translations right now. With 'Authentication' it's the same in all English.. oh well.

Or maybe just 'Client Auth'?

I suggest to keep 'stealth' in the json settings name, widget names etc just for backwards compatibility, though.

Client Auth is no longer really 'stealth': in the old days, Tor Browser would not distinguish between an onion service that was offline and one that needed auth. These days, the browser private key 'pop-up' dialog appears, which implicitly means 'there is an onion service running' - so the 'stealth' element has been sacrificed in the name of better UX.

Any strong thoughts?

**Comment by micahflee** [comment]
I agree-- though I think we may have already stopped referring to it as stealth :). I think that specific string may be obsolete, and right now UI for disabling client auth is a checkbox that says "This is a public OnionShare service (disables private key)".

**Comment by mig5** [comment]
Good point! I think we had a script that removes unused strings from all the locales? Maybe we should re-run that, as I imagine it will save translators time and effort needlessly translating strings we don't actually use anymore.
