### ISSUE TITLE
onionshare 2.5 Mac os download is missing version number

### ISSUE THREAD

**Issue by suschizu** [onionshare/onionshare#1509]
hello - I've noticed that the version numbers are missing in download https://github.com/onionshare/onionshare/releases/download/v2.5/OnionShare-2.5.dmg

the info.plist file should contain a CFBundleShortVersionString and CFBundleVersion
<img width="249" alt="Screenshot 2022-01-18 at 17 15 55" src="https://user-images.githubusercontent.com/16004333/149976121-5ca6421f-a540-4dde-be9c-0db84cd46b42.png">

**Comment by core-code** [comment]
confirmed finally fixed in 2.6.1
