### ISSUE TITLE
"Command filtered" on download attempt with Whonix in QubesOS

### ISSUE THREAD

**Issue by maltfield** [onionshare/onionshare#1511]
Unfortunately, I was not able to download a file shared with me using Onion Share -> Tor Browser today. When I accessed the .onion in Tor Browser, it prompted for the private key. When entered incorrectly, it gave me an auth error. When entered correctly, it just said:

```
Command filtered
```

### Steps to reproduce

1. Have someone share a file with OnionShare
2. In Whonix 16 on QubesOS 4.0, attempt to connect to the OnionShare `.onion`
3. Enter the Private Key for the `Onion Services Authentication`
4. Get error `Command filtered`

When I downloaded the self-contained [Tor Browser release from torproject.org](https://www.torproject.org/download/) in an AppVM (thus running another, local copy of the tor daemon as opposed to going through the VM-isolated Whonix Gateway's tor daemon), it connected fine without the issue.

Both my Whonix Workstation and my self-contained Tor Browser used Tor Browser v11.0.4.

**Comment by maltfield** [comment]
I'm creating this ticket because the error `command filtered` was pretty terse, and googling for

```
"onion share" "command filtered"
```

...produced no results.

This may or may not be related to #1309

**Comment by mig5** [comment]
Hi,

This is not an OnionShare issue - it's unique to Whonix and how it controls requests to Tor. 

The same would be true for any onion service being accessed via Whonix that uses client authentication - even if the onion service wasn't served by OnionShare.

Please have a read of the Whonix documentation which explains the fix: https://www.whonix.org/wiki/Onion_Services#Onion_Service_Authentication_Client_Setup . In your case, you want to paste the private key in a file called `1.auth_private` and then follow the instructions

If you still have trouble, consider asking on the Whonix forum (others have had the same issue which is how I found the documentation, e.g https://forums.whonix.org/t/authenticated-onion-service-not-working-using-old-or-new-methods/13110/4)

**Comment by mig5** [comment]
Added an update above, but adding it again here to force the notification. The 1.auth_private file, for Whonix, would need to contain some extra info:

In your case, you want to paste the private key in a file called `1.auth_private` and then follow the instructions. However, the `1.auth_private` file needs to contain a couple of extra parameters:

```
onion-url-without-dot-onion:x25519:private-key
```

For example, if your onion service is `yvhz3ofkv7gwf5hpzqvhonpr3gbax2cc7dee3xcnt7dmtlx2gu7vyvid.onion`, and your private key is `FOW7XIWR76UUUPXIHLMWCKEGZLIKPUWFLKDX4T2VEF7QFR6ZVCVQ`, then your `1.auth_private` file to import into Whonix Gateway should look like this:

```
yvhz3ofkv7gwf5hpzqvhonpr3gbax2cc7dee3xcnt7dmtlx2gu7vyvid:x25519:FOW7XIWR76UUUPXIHLMWCKEGZLIKPUWFLKDX4T2VEF7QFR6ZVCVQ
```

**Comment by maltfield** [comment]
Any chance you can update your documentation FAQ with this?

**Comment by adrelanos** [comment]
Tracking this issue here:
https://forums.whonix.org/t/onionshare-whonix-integration-development-discussion/300/37

This has been specifically documented just now:
https://www.whonix.org/wiki/OnionShare#Visit_Authenticated_OnionShare_Services_using_Tor_Browser_in_Whonix

OnionShare used to have a feature `error_tor_protocol_error`:

    "error_tor_protocol_error": "Error talking to the Tor controller.\nIf you're using Whonix, check out https://www.whonix.org/wiki/onionshare to make OnionShare work.",

But seems that got broken?

**Comment by mig5** [comment]
Hi Patrick, we still raise that error on TorErrorProtocolError

https://github.com/onionshare/onionshare/blob/1385aa068f1ef41f67a0cee4eff61bc126346d4e/desktop/onionshare/gui_common.py#L498-L499

which itself is raised if ProtocolError (returned from Stem) is raised:

https://github.com/onionshare/onionshare/blob/1385aa068f1ef41f67a0cee4eff61bc126346d4e/cli/onionshare_cli/onion.py#L753-L755

I guess this particular error doesn't raise ProtocolError at the Stem level (meaning the Tor control port didn't make Stem raise it).
