### ISSUE TITLE
Hosting A Website With Onionshare

### ISSUE THREAD

**Issue by driggerspaxton** [onionshare/onionshare#1521]
I just downloaded onionshare, I uploaded an html file to host a website, and everytime I go to the link, it even shows me the name I chose to the name the site and gives me the option to open up the html file, but whenever I go to open up the html file, and wait for it to load, I'm given this message : Sorry, an unexpected error seems to have occurred, and your request didn't succeed. Any help would be greatly appreciated. I'd also really appreciate if someone could explain the index.html and the importance of it, and what it should be. I'm new to all of this and any assistance will be greatly appreciated.

**Comment by driggerspaxton** [comment]
Hi, I've been trying to upload a file using "Host a Website" Feature but when clicking on the file name I get this message "Sorry, an unexpected error seems to have occurred, and your request didn't succeed",
This happens with any file whether its type is .pdf or .txt or any other type. Please, if anyone can help me, I'd really appreciate it. I've been working on this all night and all day

**Comment by driggerspaxton** [comment]
Y'all I'm seriously out of ideas and I've tried everything at this point.

**Comment by sqbi-q** [comment]
Works fine on OnionShare 2.5 (Linux Manjaro). Both .pdf and .txt formats work. Couldn't reproduce the issue.

>I'd also really appreciate if someone could explain the index.html and the importance of it, and what it should be. I'm new to all of this and any assistance will be greatly appreciated.

`index.html` is file written in [HTML](https://en.wikipedia.org/wiki/HTML) that is downloaded and rendered as first when entering website. You don't need `index.html` for hosting mode to work (you will be redirected to directory listing).

**Comment by driggerspaxton** [comment]
Im using Windows 10. The adress to the website is http://jv745fjj7nf757iwwi65lnc4cqb2ap2uqumqoruzxbq3ad567whbypyd.onion

**Comment by driggerspaxton** [comment]
I still can't get it, Ive tried uploading it as a text file, a pdf file, an html file. Its weird, I can still host chats, Im not sure about file sharing, but website hosting will not work to save my life man. I even renamed the html file index.html onmce to see if that made a difference and it didn't. Ive tried to get this to work for 8 hours straight, looked up every video I can find, and read every piece of literature, and so far, I haven't found anything.

**Comment by sqbi-q** [comment]
Run OnionShare from CMD with verbose flag (`onionshare -v` but if you didn't set environment variable then you need to refer to path of OnionShare) and copy its output when importing files, running web hosting mode and trying to connect.

It is server side problem apparently.

![image](https://user-images.githubusercontent.com/48880676/151702992-211267ef-cf16-4f83-a645-af5e6ae97a69.png)

**Comment by driggerspaxton** [comment]
Hey man, I really appreciate you for your responses and for your help, but I can't even get Onionshare to run from cmd prompt, (its not onionshare, or onionshare.exe), and I dont know anything about environment variables or how to set them, and I really dont know much about all this. I'm really starting to doubt whether I'll be able to get this done. Thank you for your help though, youve been the only one and youve tried, I just dont know what else to try, and I'm kind of getting close to the edge of my own personal capabilities.

**Comment by driggerspaxton** [comment]
I'm open to any suggestions and I'm even willing to break everything down and learn it step by step, I just know thats a major inconvenience and I wouldn't want to ask you to do that. But if you, or anyone else is willing to go through all that or has anymore suggestions, I'll give it my best shot

**Comment by driggerspaxton** [comment]
How would I run it in CMD and what exaclty should I do?

**Comment by driggerspaxton** [comment]
Hey, if anyone can help, id greatly appreciate anything

**Comment by driggerspaxton** [comment]
Whenever I choose to inspect it, these are the warnings I receive:

Content Security Policy: The page’s settings blocked the loading of a resource at data: (“media-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data: (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data: (“media-src”).

**Comment by driggerspaxton** [comment]
This is the new website address, and the exact same issue:

http://3azbe2fgbl2u6l72utpwzvbaidkmnmkqkoxwm6gk5agrmsodxrm4buid.onion/

**Comment by driggerspaxton** [comment]
I've tried literally everything I know to do, and I'm still getting the same error each time

**Comment by driggerspaxton** [comment]
if there's anything anyone can suggest or add to this, I'd really appreciate it.
