### ISSUE TITLE
Webseite hosten

### ISSUE THREAD

**Issue by 123luki** [onionshare/onionshare#1522]
Hallo 
Wenn ich eine Webseite Hosten möchte, werden die dateien als verzeichnissstrucktur angezeigt. mache ich da einen Fehler?
Danke für die Hilfe
![Screenshot 2022-02-03 194132](https://user-images.githubusercontent.com/92298191/152407837-228ec1b3-4b6d-448e-b422-087dcdf36416.jpg)
![Screenshot 2022-02-03 194233](https://user-images.githubusercontent.com/92298191/152407993-05838ccd-4ef6-412c-a1c2-21f3f6235054.jpg)

**Comment by mig5** [comment]
Hallo! Versuchen Sie, Ihre Index.html-Datei in index.html umzubenennen .

**Comment by 123luki** [comment]
hallo. Viele dank nun werden die Ordner nichtmehr angezeigt dafür eine Fehlermeldung. 
![Screenshot 2022-02-08 175935](https://user-images.githubusercontent.com/92298191/153037364-cdea26f3-d896-40f3-9ae2-14d847e45c11.jpg)
g

**Comment by mig5** [comment]
#1512
