### ISSUE TITLE
Installing the ubuntu focal onionshare package is missing requests

### ISSUE THREAD

**Issue by brassy-endomorph** [onionshare/onionshare#1528]
On Ubuntu 20.04, after using `apt` to install onionshare, use of the `onionshare-cli` throws an `ImportError` on `requests`, but this should be included as a dependency.

**Comment by mig5** [comment]
We no longer release .deb packages/PPA for onionshare. The recommended way to install CLI on Linux is via pip, by using the snap or flatpack files, or from source.

Requests is already defined as a dependency in this upstream project (https://github.com/onionshare/onionshare/blob/main/cli/pyproject.toml#L25)

If there is a downstream deb package maintained, e.g in Ubuntu or Debian, where this dependency issue exists, this issue may best be reported to the developer/team responsible for packaging it (none of the core OnionShare developers are involved with packaging debs for those distros)
