### ISSUE TITLE
Old version of Tor?

### ISSUE THREAD

**Issue by AngelHair** [onionshare/onionshare#1529]
I am once again setting up an OnionShare command line server on Ubuntu 20.04.3 LTS (cli only) running on a Raspberry Pi per the instructions on Micah Lee's blog site.  However, after I install Tor and then run OnionShare, I get the following error message:

"Your version of Tor is too old, stealth onion services are not supported"

I did an update / upgrade of Ubuntu on this device, but it still has the old version of Tor, I guess since that is all that is in the repositories. I am not sure how to get a newer version from the command line, and I cannot find instructions on how to do so.

I tried the instructions from here, as suggested in the OnionShare website docs:

https://support.torproject.org/apt/tor-deb-repo/

but that failed with the following errors:

E: The repository 'https://deb.torproject.org/torproject.org/(lsb_release -cs) Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

At this point I am lost.

Could you possibly post instructions on how to get the current version of Tor on Ubuntu via the command line so that Onionshare will work with command line Ubuntu on a Raspberry Pi?

**Comment by mig5** [comment]
`E: The repository 'https://deb.torproject.org/torproject.org/(lsb_release -cs) Release' does not have a Release file.`

That looks like you've literally got `(lsb_release -cs)` in the `/etc/apt/sources.list.d/tor*.list` file. That's meant to be an interpolated variable, e.g what you get when you type `lsb_release -cs` on the command line in a terminal by hand.

In fact https://support.torproject.org/apt/tor-deb-repo/ doesn't even interpolate it anymore, they say to run it by hand and replace the example of DISTRIBUTION with the output. So not sure how you ended up there, but maybe run through the Tor deb instructions again. 


If you still get issues after upgrading to the latest version of Tor, there's a chance that you still get this error, but can be if your installation of OnionShare dragged in a copy of python3-stem which doesn't have support for Client Auth (stealth) on v3 onions. It's unfortunately a misleading message, in that case. But if you installed OnionShare via flatpak or snap, or via pip per any of the links below, it should not be an issue.

https://docs.onionshare.org/2.5/en/install.html 
Or install the CLI version by itself, using pip: https://docs.onionshare.org/2.5/en/advanced.html#cli

**Comment by ilf** [comment]
I can confirm this with onionshare 2.6 and tor 0.4.7.13.

```
$ onionshare-cli --receive --website
<snip>
Connecting to the Tor network: 100% - Done
Your version of Tor is too old, stealth onion services are not supported
```

See Arch: https://bugs.archlinux.org/task/74545
