### ISSUE TITLE
Tor Browser 11.0.6 breaks OnionShare

### ISSUE THREAD

**Issue by AngelHair** [onionshare/onionshare#1530]
I got OnionShare running on my Raspberry Pi / Ubuntu cli machine, and it worked fine accessing it with Ubuntu Tor Browser 11.0.4, but not with Ubuntu Tor Browser Tor Browser 11.0.6.   Then my machine with Ubuntu Tor Browser 11.0.4 automatically upgraded to version 11.0.6, and now it no longer works with OnionShare.  When I enter the Private Key it gives error "Unable to configure Tor with your key"

![Screenshot from 2022-02-18 06-24-58](https://user-images.githubusercontent.com/14369583/154673829-1b4d67e7-60a8-4a39-8839-686098fd3bfe.png)
"

**Comment by mig5** [comment]
Yep, unfortunately it's not our bug though, it's a bug in Tor Browser. I reported it upstream https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40802 - nothing you can do but use an older version of TB (probably not secure) or use 'public mode' OnionShare services that don't use private keys.

**Comment by mig5** [comment]
Another option that you have: use the Alpha version of Tor Browser from https://www.torproject.org/download/alpha/ . I have just tested it on Linux and it doesn't suffer the same bug as Tor Browser 11.0.6, though being alpha, it might contain other bugs.

**Comment by hp528122** [comment]
hey i have tested with alpha version of it...it still showing unable to configure tor with your key

@mig5 can you help me with that..email me on no528123@gmail.com[](url
![Screenshot_1](https://user-images.githubusercontent.com/53688936/156709733-e3fdc337-655f-45bd-8014-4d0833b1dc93.png)
)

**Comment by mig5** [comment]
It is no longer working for me in the alpha either, sorry. Perhaps at the time I was somehow using an earlier alpha release where it still worked.

**Comment by hp528122** [comment]
okay,@mig5 if it working on your device, then can you share me your alpha tor version at @hp528122 git account...it will be helpful

**Comment by mig5** [comment]
It's not working on my device anymore. I must've been on an older version of the Tor Browser alpha before the bug appeared there too (later).

The bug has been fixed and will be released in Tor Browser 11.0.8 which is expected next week.

**Comment by hp528122** [comment]
The bug has been fixed and will be released in Tor Browser 11.0.8 which is expected next week.....okay thanks buddy for the information
