### ISSUE TITLE
Figure out new way to shutdown flask service

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1542]
When we stop an OnionShare service, this `web.force_shutdown()` function is run:

```python
    def force_shutdown(self):
        """
        Stop the flask web server, from the context of the flask app.
        """
        # Shutdown the flask service
        try:
            func = request.environ.get("werkzeug.server.shutdown")
            if func is None and self.mode != "chat":
                raise RuntimeError("Not running with the Werkzeug Server")
            func()
        except Exception:
            pass

        self.running = False

        # If chat, shutdown the socket server
        if self.mode == "chat":
            self.socketio.stop()
```

I noticed when running tests we get this warning:

```
  /home/circleci/repo/cli/onionshare_cli/web/web.py:342: UserWarning: The 'environ['werkzeug.server.shutdown']' function is deprecated and will be removed in Werkzeug 2.1.
```

I looked into this, and they give their rationale for deprecating this here: https://github.com/pallets/werkzeug/issues/1752

Also, we should probably run Flask in production instead of dev.

**Comment by mig5** [comment]
[Waitress](https://docs.pylonsproject.org/projects/waitress/en/stable/) might be interesting?

Flask's own ['Deploy to Production'](https://flask.palletsprojects.com/en/2.0.x/tutorial/deploy/) doc now mentions it.

Apparently the 'wsgiapp' parameter passed to `serve()` in https://docs.pylonsproject.org/projects/waitress/en/stable/usage.html can be the Flask app:

https://stackoverflow.com/questions/58923634/use-waitress-as-a-production-server-for-flask
https://stackoverflow.com/questions/51045911/serving-flask-app-with-waitress-on-windows
