### ISSUE TITLE
Add version information to the Windows executable

### ISSUE THREAD

**Issue by meypi** [onionshare/onionshare#1546]
Hello,

For software update monitors it would be usefull if the .exe file contained the version of OnionShare.

Please consider adding it to the onionshare.exe file.

![image](https://user-images.githubusercontent.com/99614822/158026055-44e4c3a4-4549-449e-b739-029b9f7eb375.png)

Kind regards.

**Comment by SaptakS** [comment]
Hi @meypi, I am actually able to see both file description and file version in my windows OS (as shown in screenshot below). I am in Windows 11 in win-64, using OnionShare 2.6. Can you tell me the OnionShare version and the windows system you are using? That will help me in debugging

![Screenshot from 2023-09-05 16-49-12](https://github.com/onionshare/onionshare/assets/9530293/c42e39ff-a85a-41e1-a29d-27210d707c24)

**Comment by meypi** [comment]
The version of the program seems to be inserted, nothing more to do here, thank you, the thread can be closed.
