### ISSUE TITLE
Onionshare GUI does not start

### ISSUE THREAD

**Issue by Smojo** [onionshare/onionshare#1549]
After installing Onionshare Flatpak version (2.5) it started only one time.

I tried to share a file (moved it into the GUI via drag and drop) and after a message, that this is not supported yet (/ for my OS / for this version ... don't remember exactly) the windows disappeared. I thought it crashed eventually, so I tried to restart it, but now it is not working anymore. Also a reboot of the system did not help. Any idea what can be wrong?

When I click on the .desktop Icon under apps, nothing happens.

Thx in advance.

- _PureOS 10 – Byzantium
 -- based on Debian 11 (Bullseye)
 -- Kernel - Linux 5.10.0-12-amd64
 -- Gnome 3.38.5 (Window System: Wayland)_

**Comment by mig5** [comment]
Try removing any .lock file in `~/.config/onionshare/` . This will likely resolve the 'inability to start the app again' issue. See #1374

**Comment by brotheralameen1** [comment]
Got it. Thanks.

**Comment by Calandiel** [comment]
> There is no onionshare directory in /home/.config/

Try deleting `~/.var/app/org.onionshare.OnionShare/config/onionshare/lock`
