### ISSUE TITLE
Onion service info

### ISSUE THREAD

**Issue by mubashar1199** [onionshare/onionshare#1551]
Hello, 
Sorry for putting it here but i need some information, i need to create an ios app for anonymous chat using sockets where share can share their .onion addresses with each other and then using this address they can chat in the app.
I believe that current version of this project is not applicable to IOS, what changes i need to make to achieve my goals?
Thanks

**Comment by mig5** [comment]
Sorry, that's too broad a question for this project. You won't be able to modify this app (written in python) to suit your needs on IOS. To make an IOS app means a completely different codebase, programming language, in other words a total rewrite from scratch.

You might be interested in https://github.com/onionshare/onionshare-ios, which is the IOS app for OnionShare that we have a team working on, and is currently available as a Testflight app. However, that app is currently limited to only sharing files or 'website mode' - not Chat Mode. So even that won't be enough, but you might be able to take inspiration or help work on that project to add Chat / socket support. Feel free to look at the code, and soon you'll be able to test it out (keep an eye on the https://onionshare.org website for information about mobile support coming soon)
