### ISSUE TITLE
Start releasing separate 32-bit and 64-bit Windows binaries

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1557]
Windows 11 is 64-bit only. I think we should start releasing 64-bit binaries, and eventually when Windows 10 is end-of-life phase out 32-bit binaries.

It sure would be nice to automate the Windows dev environment/release process a bit more than it currently is, so it will be simpler to make 32-bit and 64-bit releases on the same machine. This will take some work to figure out the best way to do it.

**Comment by mig5** [comment]
Resolved as of v2.6! https://github.com/onionshare/onionshare/releases/tag/v2.6
