### ISSUE TITLE
OnionShare 2.5 on Windows won't update/run - 'ImportError: Module use of python37.dll conflicts with this version of Python'

### ISSUE THREAD

**Issue by GlydetheSurfer** [onionshare/onionshare#1572]
I've been having issues to where every time i try to update onion share.. it still runs 2.4 when it should be using 2.5 no matter how many times i download the 2.5 msi installer... so then i uninstall python and everything related to onion share. and then i reinstall onion share and now this pops up... 
![image](https://user-images.githubusercontent.com/32045132/163312039-7d3de881-8dc9-477c-afc2-42f5e56d81b7.png)
Idk what to do.. all i want is onion share up to date and working. i've been at this ALL DAY.

**Comment by GlydetheSurfer** [comment]
it seems its not an issue with python... but its an issue with only onionshare 2.5, 2.4 works just fine... latest version of onionshare needs to be fixed

**Comment by shahn** [comment]
I had exactly the same issue when using the MSI installer with an older version of onionshare already installed. Uninstalling both versions followed by only installing v2.5 solved the issue for me. Seems to be an installer bug where the old installation is not updated, but a new installation is placed next to the old installation which then fails to run.

**Comment by GlydetheSurfer** [comment]
> I had exactly the same issue when using the MSI installer with an older version of onionshare already installed. Uninstalling both versions followed by only installing v2.5 solved the issue for me. Seems to be an installer bug where the old installation is not updated, but a new installation is placed next to the old installation which then fails to run.

but i tried that. it wont run at all, it just shows that error window.

**Comment by shahn** [comment]
I would assume that something (might not be onionshare) has left some conflicting python installation behind. Probably better debugging of which Python versions are actually used for what would be required to figure out your issue, I guess.

**Comment by mig5** [comment]
Hopefully this is resolved as of 2.6.1 . Please re-open if not.
