### ISSUE TITLE
OnionShare: Trying to host simple index to no avail

### ISSUE THREAD

**Issue by Plugadrip** [onionshare/onionshare#1575]
I've made a simple index, as simple as it gets, no assets, just the HTML file. And I get the "Sorry, an unexpected error seems to have occurred, and your request didn't succeed." I've added the the necessary pictures for you to look at.

Please someone help, I am extremely new to this stuff and willing to learn but just want to be able to host a simple HTML site.

[https://imgur.com/a/r9XL0Fb](url)

Is there something I'm doing wrong?

**Comment by mig5** [comment]
Hi,

If you're on Windows, this is a known bug in the latest release of OnionShare. See https://github.com/onionshare/onionshare/issues/1512

It has been fixed in the source and the next release will work.

**Comment by Axiomsense** [comment]
Does anyone, anywhere know when the next release will be coming out?

**Comment by SaptakS** [comment]
@micahflee is working towards automating build and packaging for different OS. Once that's done, there should be an alpha release.

**Comment by mig5** [comment]
Closing as duplicate of https://github.com/onionshare/onionshare/issues/1512
