### ISSUE TITLE
Outdated runtime

### ISSUE THREAD

**Issue by peter099** [onionshare/onionshare#1579]
When i run `flatpak update` i get this:

```
Info: org.kde.Platform//5.15 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   org.onionshare.OnionShare
```

**Comment by peter099** [comment]
I still get this message. Can this cause security issues?

**Comment by mig5** [comment]
@micahflee is this one resolved in the latest flatpak fixes?

**Comment by mig5** [comment]
As far as I can tell, this message doesn't come up anymore on the 2.6 release for Flatpak. (We are now using 5.15-21.08 which as far as I can tell is the latest and is not EOL)
