### ISSUE TITLE
Unable to open "Share Files" link

### ISSUE THREAD

**Issue by ingfabby** [onionshare/onionshare#1584]
On a Windows Laptop with Onion share installed:
1. I select the option "Share Files"
2. I select a .jpg file to be shared
3. Click on "Start Sharing"
4. Link and code are generated
5. I copy-paste the link on Tor Browser for Android running on a Galaxy S20 with Android 12
6. I get the message " Unable to connect". I get the same results when I try to host a Website.

**Comment by mig5** [comment]
What happens if you use 'Public mode', so that no Private Key is generated? (I assume that's what you mean by 'code')

**Comment by ingfabby** [comment]
I was able to download the file after disabling the Private Key on Tor Browser for Android, I can not test on the Tor Browser desktop, because my computer does not allow me to have both apps connected to Tor at the same time. Is there a way around that?

**Comment by mig5** [comment]
For the computer, you could configure the OnionShare settings to use Tor Browser as the Tor connection method. (if what you mean is that your computer somehow blocks two separate Tor processes from running at once)

But the core of your issue about access on your Android sounds like the Tor Browser for Android client doesn't support Client Authentication. We have no solution for that, you'll have to raise it with the Tor Browser for Android developers. The use of the computer was just to debug that it wasn't an issue with OnionShare (sounds like it isn't).

**Comment by ingfabby** [comment]
I manage to connect the OnionShare app through the Tor Browser, but none of the features worked after that, all of them stayed on the loading stage.

**Comment by mig5** [comment]
I'm not sure what 'the loading stage' means. Ultimately I think the core issue was that Tor Browser for Android doesn't/didn't support Client Authentication, which we can't do anything about.

If there are still issues using the shortly-to-be-released OnionShare v2.6 on Windows with 'Tor Browser' as its tor connection method, please let us know, but we haven't reproduced that last issue mentioned.
