### ISSUE TITLE
Request to get a flatpak for raspbian on the raspberry pi

### ISSUE THREAD

**Issue by cyberlink1** [onionshare/onionshare#1591]
Tried to install it on a raspberry pi running raspbian but it appears the flatpak is not there for it.

Would be nice to be able to put it on the raspberry pi just due to it's small size, low power requirements, etc.

**Comment by mig5** [comment]
@micahflee will 2.6 run on a Raspberry Pi ? (maybe via the snap?)

**Comment by mig5** [comment]
And he just answered my question, I think: https://micahflee.com/2022/10/new-censorship-circumvention-features-come-to-onionshare-26/

Please try it! And reopen (or make a new issue) if there's a problem with it. Thanks!
