### ISSUE TITLE
Help to transfer Website v3 URL address from one device to another.

### ISSUE THREAD

**Issue by JonathanCulburra** [onionshare/onionshare#1596]
I have successfully run a v3 website using onionshare for a while now, but I would like help to get a backup copy of the v3 address to run on another device. I'm transferring from windows 8.1 64-bit to Windows 10 64-bit. Is there a way I can do this or should I only keep a backup URL on the second device?

Also, Is there future   ##development for including a customizable domain name feature? Eg. creating a valid URL for the website with customizable first few characters?
Thanks. Any help is appreciated.

**Comment by mig5** [comment]
Hi @JonathanCulburra 

If you are effectively wanting to backup and restore your onionshare data on another machine, you want to copy across the `AppData\Roaming\OnionShare\` directory - at least the 'onionshare.json' file, and the 'persistent' directory, inside which is where your 'persistent' onion setting (including the hostname and private key) are stored. 

You don't need to copy the `tmp`, `tor_data` or `events` folders, and you should make sure *not* to copy any 'lock' file in the OnionShare folder (this file is normally only present while you are running OnionShare, but if it's copied to your new machine, OnionShare might not start properly)

We are not currently considering making a 'customizable domain name feature', in an effort to keep the complexity of the code (which is already considerable) as simple as possible. There are other tools that exist for this purpose, and it's possible to change an onion address/private key in the OnionShare settings with a pre-prepared onion address/key (see https://github.com/onionshare/onionshare/issues/1550 for an example of someone who wanted to do that)

**Comment by JonathanCulburra** [comment]
Thank you. Sorted!
