### ISSUE TITLE
Program can't start...missing api-ms-win-core-path-l1-1-0.dll

### ISSUE THREAD

**Issue by aj24hanlo** [onionshare/onionshare#1598]
Windows 7 Professional 64-bit on an Intel Xeon CPU X5670 2.93GHz and 12.0 GB RAM

Tried uninstalling and reinstalling several times and keep getting the same error. If my OS is too old, I know, so just say so. Gotta get a new PC, but have been putting it off because of the time and cost involved.
![OnionShare](https://user-images.githubusercontent.com/108597508/177020495-ad19ed15-16de-4226-8f50-99cb135435bd.jpg)

**Comment by mig5** [comment]
Sorry, but it does sound like this is a problem with Windows 7 and Python 3.9.

https://superuser.com/questions/1660386/api-ms-win-core-path-l1-1-0-dll-is-missing-from-your-computer
