### ISSUE TITLE
Update onionshare for congestion control (Tor 0.4.7.8)

### ISSUE THREAD

**Issue by mikeperry-tor** [onionshare/onionshare#1604]
Tor finally released support for congestion control in the 0.4.7 series: https://blog.torproject.org/congestion-contrl-047/

Onionshare needs to update to 0.4.7 in order for its onion services to use congestion control.

We're still tuning this system for increased performance, but it is already ~2X faster than 0.4.6. This tuning will not require additional upgrades.

The 0.4.7 series also provides vanguards-lite by default, which will mitigate Guard discovery attacks against onionshare onion services.

**Comment by mig5** [comment]
Thanks @mikeperry-tor ! Yep, we've actually updated our develop branch to fetch Tor binaries out of the Tor Browser 11.0.15 release. So the next OnionShare release (which is 'imminent') will contain this version for bundled Tor.

Thanks for all the work on congestion control!

> The 0.4.7 series also provides vanguards-lite by default, which will mitigate Guard discovery attacks against onionshare onion services.

Do we need to do any configuration for that (I recall the original Vanguards being a separate process to be run in the past, but I might be mistaken?), or do you mean 'by default' it will work out of the box within the Tor process itself with nothing else required, on this series?

**Comment by mikeperry-tor** [comment]
As a heads up, there will be a Tor 0.4.7.9 next week. It is worth waiting to pick up that one, at this point.

**Comment by mig5** [comment]
Thanks for the heads up @mikeperry-tor . We're moving a bit slowly on getting a release out the door :s in this case, sounds lucky this time

**Comment by mig5** [comment]
I'm going to close this out, as the 2.6 release of OnionShare will have the latest version of Tor bundled with it (for Windows/macOS and the Linux snap/flatpak builds).
