### ISSUE TITLE
Refactoring required to upgrade Flask

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1614]
I attempted to upgrade Flask to the latest version, 2.2.2, but this causes a regression bug in OnionShare. The latest version of Flask that doesn't cause this regression is version 2.1.3, so I'm upgrading to that instead. Here's the bug.

In `cli/onionshare_cli/web/web.py`, after the Flask app is first created (`self.app`), the constructor runs `self.generate_static_url_path()`, which generates a new random URL for the static URL path. This works in the CLI, and work for the first time in the desktop app.

But if you open a tab, start a service, stop the service, then start it again, it crashes with:

```
[Sep 30 2022 02:42:17 PM] Web.generate_static_url_path: new static_url_path is /static_oc2qd4qj3exlekq5ryb63dkiwq
Traceback (most recent call last):
  File "/home/micah/code/onionshare/desktop/onionshare/threads.py", line 66, in run
    self.mode.web.generate_static_url_path()
  File "/home/micah/code/onionshare/cli/onionshare_cli/web/web.py", line 200, in generate_static_url_path
    self.app.add_url_rule(
  File "/home/micah/.cache/pypoetry/virtualenvs/onionshare-BFLClbuE-py3.10/lib/python3.10/site-packages/flask/scaffold.py", line 49, in wrapper_func
    self._check_setup_finished(f_name)
  File "/home/micah/.cache/pypoetry/virtualenvs/onionshare-BFLClbuE-py3.10/lib/python3.10/site-packages/flask/app.py", line 722, in _check_setup_finished
    raise AssertionError(
AssertionError: The setup method 'add_url_rule' can no longer be called on the application. It has already handled its first request, any changes will not be applied consistently.
Make sure all imports, decorators, functions, etc. needed to set up the application are done before running it.
```

This is because the desktop code tries calling `web.generate_static_url_path()` after the app has already been set up, and there's a check to prevent this from working in newer versions of Flask. Specifically, the `_check_setup_finished` method is new:

https://github.com/pallets/flask/blob/a1c478bc93d3dc018a6e7a1ba3cf5409553c9df3/src/flask/app.py#L720-L730

The correct solution would be to regenerate the whole Flask app (`self.app`) instead of just updating the existing one, but I ran into problems with that. So instead, I'm opening an issue for the future and sticking with Flask 2.1.3.

**Comment by micahflee** [comment]
I ran into yet another problem with Flask 2.1.3. In receive mode, the server wouldn't actually close when it was supposed to, and there might be more issues as well. So I've reverted back to Flask 2.0.3. I think upgrading Flask will require some careful work.

**Comment by thomasgoirand** [comment]
Hi. In Debian, we'd like to upgrade to Flask 2.2.2. Could you please do the work to fix compat with that version of Flask, rather than hiding the dust under the carpet please? :)

Cheers,

Thomas Goirand

**Comment by HLFH** [comment]
@micahflee 

It is true there is a new setupmethod behavior.

On our app, we fixed it: https://github.com/HLFH/automua/commit/5158b6ef71d22e206588e8e83c1f44752e9a12d1

We had to set the app under the [basic application factory create_app](https://flask.palletsprojects.com/en/2.2.x/patterns/appfactories/).

> If you move the creation of the application object into a function, you can then create multiple instances of this app later.
> So why would you want to do this?
> Testing. You can have instances of the application with different settings to test every case.

> Multiple instances. Imagine you want to run different versions of the same application. Of course you could have multiple instances with different configs set up in your webserver, but if you use factories, you can have multiple instances of the same application running in the same application process which can be handy.

**Comment by jefferyto** [comment]
It would be great if this can be revisited. I'm working on updating packages for OpenWrt and having to hold back our Flask package is not ideal.
