### ISSUE TITLE
"Open with" on Windows Shows Dangerzone Description instead of "Dangerzone"

### ISSUE THREAD

**Issue by deeplow** [onionshare/onionshare#1640]
![image(7)(1)](https://user-images.githubusercontent.com/47065258/205265762-8e5ac348-ebaf-43cf-9782-3814263e6066.png)

**Comment by mig5** [comment]
@deeplow should this be in the Dangerzone Github issue queue rather than OnionShare?

**Comment by deeplow** [comment]
Whoops :stuck_out_tongue:. I must have have thought I was on the Dangerzone repo. Sorry about that.

**Comment by mig5** [comment]
@deeplow I understand :D I can delete it due to elevated permissions, no worries!
