### ISSUE TITLE
Trying to Run OnionShare on Debian in Andronix on an Andorid

### ISSUE THREAD

**Issue by flotsam2000** [onionshare/onionshare#1641]
You can probably see where I'm going here. According to the Andronix folks, using flat or snap will not work in this instance. They recommended I compile a .deb version myself, but I'm not finding a ./setup.py in the cloned directory. 

End goal? 

A hidden service someone can host on an android device...

I'm doing this just to see if I can.

**Comment by SaptakS** [comment]
There is actually an android app for OnionShare in development. You can check https://github.com/onionshare/onionshare-android and https://onionshare.org/mobile/#download

**Comment by flotsam2000** [comment]
Omg, you’re beating me to it! Lol. Ok, well I’ll keep playing on my end too.

Working on a workaround making writing own setup.py to make a .deb based on the source code after downloading the zip.

If I can do this I’m going to offer $100 to anyone that can track my service to my home IP…


On Dec 9, 2022, at 11:54 PM, Saptak Sengupta ***@***.***> wrote:

﻿
CAUTION: External Sender

There is actually an android app for OnionShare in development. You can check https://github.com/onionshare/onionshare-android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fonionshare%2Fonionshare-android&data=05%7C01%7Cjosh%40pkisolutions.com%7Cff4f0195cd41402ace6d08dada83d1f6%7Cd586bf77b478489a91588e76a9a6d281%7C0%7C0%7C638062556970164530%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8RcrtgPIP8ykX8VbX2lf%2FA51hcHuHije5rMPt8CVyQ0%3D&reserved=0> and https://onionshare.org/mobile/#download<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonionshare.org%2Fmobile%2F%23download&data=05%7C01%7Cjosh%40pkisolutions.com%7Cff4f0195cd41402ace6d08dada83d1f6%7Cd586bf77b478489a91588e76a9a6d281%7C0%7C0%7C638062556970164530%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IOMzvgXdjsw%2BI1sSIXNUQtWXORB4mvDGK1YxZGT2p5o%3D&reserved=0>
