### ISSUE TITLE
OnionShare v2.6 does not auto-connect to Tor at all on my Windows 10 OS

### ISSUE THREAD

**Issue by FreddyQueen** [onionshare/onionshare#1651]
Hi ! 
I have 3 files to share worldwide through the persistent sharing feature. I'd like OnionShare to connect to Tor and begin sharing without my assistance. How can I set it up ? 
I am running 2.6 version and each time I launch the app, OnionShare starts but I have to click on "Connect to Tor" (wherease Auto-Connect is enabled as shown on the snapshot below)  and then click on "Start sharing"... 
In a word, I have 2 questions 
1) Why OnionShare v2.6 does not auto-connect to Tor at all?  How to fix it ?
2) How to enable auto-sharing (if the feature exists ; if not, could the editors add it for the next updates) ?)
Thanks. Cheers.

![OnionShare3](https://user-images.githubusercontent.com/121929714/213119892-02cd0d04-0faa-4d27-b793-f648c617e1d6.jpg)
![OnionShare1](https://user-images.githubusercontent.com/121929714/213121898-aa6c97d5-79f0-483b-844a-a1a0812a2f24.jpg)

**Comment by SaptakS** [comment]
It definitely should auto-connect. I verified that it is working in my Debian OS. I will test it out in windows and check if there is some bug.
