### ISSUE TITLE
Issues with Brave Browser via Tor

### ISSUE THREAD

**Issue by Taipo** [onionshare/onionshare#1657]
When configuring OnionShare Receive Files to be private (not public) the URL loads in TorBrowser but for some reason will not load in Brave. When selecting the Public Share Service setting, the upload site becomes available in both Brave and TorBrowser

**Comment by mig5** [comment]
This implies that Brave Browser does not have native support for Client Authentication onion services. There is nothing OnionShare can do about that.

I'll see if we can reach out to the Brave developers to confirm this, but ultimately it's up to Brave to support that option.

**Comment by Taipo** [comment]
Thanks for that
