### ISSUE TITLE
Inaccurate Warning Message:

### ISSUE THREAD

**Issue by avocadodavinci** [onionshare/onionshare#1712]
- When closing a tab with an active chat, the warning message states "close tab that is hosting website" instead of "close tab hosting chat."

**Suggestions:** 
- Change the warning message to read “close tab hosting chat”

![image](https://github.com/onionshare/onionshare/assets/105882615/352cd522-d846-41b7-bf20-7732c00c204b)

**Comment by mig5** [comment]
Was already fixed in https://github.com/onionshare/onionshare/pull/1702
