### ISSUE TITLE
Compatibility with Werkzeug 3

### ISSUE THREAD

**Issue by coogor** [onionshare/onionshare#1809]
Hi,
I'm getting errors in the test section after Werkzeug was switched to version 3:
[   17s] + pytest -v -k 'not test_large_download' -rs tests
[   18s] ImportError while loading conftest '/home/abuild/rpmbuild/BUILD/onionshare-2.6/cli/tests/conftest.py'.
[   18s] tests/conftest.py:8: in <module>
[   18s]     from onionshare_cli import common, web
[   18s] onionshare_cli/__init__.py:30: in <module>
[   18s]     from .web import Web
[   18s] onionshare_cli/web/__init__.py:21: in <module>
[   18s]     from .web import Web
[   18s] onionshare_cli/web/web.py:40: in <module>
[   18s]     from .share_mode import ShareModeWeb
[   18s] onionshare_cli/web/share_mode.py:32: in <module>
[   18s]     from werkzeug.urls import url_quote
[   18s] E   ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/lib/python3.11/site-packages/werkzeug/urls.py)

Is this something you need to fix, or was url_quote moved to a different module?
Full log:
https://build.opensuse.org/build/devel:languages:python/openSUSE_Tumbleweed/x86_64/python-onionshare/_log

**Comment by bnavigator** [comment]
Fixed in #1677

**Comment by mig5** [comment]
Thanks - since it's fixed, I'll close this out - we're just in the middle of trying to get a new release out which has proven difficult on a few fronts - hopefully very soon.

**Comment by slyon** [comment]
We're hitting this issue in Ubuntu "Noble", so a new release containing those fixes would be appreciated.

**Comment by k4r4b3y** [comment]
I am having the same error message as in the original post of this issue. Can we re-open this issue?

Here are some logs:
```
dietpi@DietPi:~$ onionshare-cli --help
Traceback (most recent call last):
  File "/usr/bin/onionshare-cli", line 5, in <module>
    from onionshare_cli import main
  File "/usr/lib/python3/dist-packages/onionshare_cli/__init__.py", line 30, in <module>
    from .web import Web
  File "/usr/lib/python3/dist-packages/onionshare_cli/web/__init__.py", line 21, in <module>
    from .web import Web
  File "/usr/lib/python3/dist-packages/onionshare_cli/web/web.py", line 40, in <module>
    from .share_mode import ShareModeWeb
  File "/usr/lib/python3/dist-packages/onionshare_cli/web/share_mode.py", line 32, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/lib/python3/dist-packages/werkzeug/urls.py)
dietpi@DietPi:~$ 
```

I am trying to run onionshare-cli inside a 32-bit Odroid HC1 single board computer, running Dietpi (debian trixie repos):
```
dietpi@DietPi 
OS: Debian GNU/Linux trixie/sid armv7l 
Host: Hardkernel ODROID XU4 
Kernel: 6.1.63-current-odroidxu4 
Uptime: 1 day, 3 hours, 10 mins 
Packages: 781 (dpkg) 
Shell: bash 5.2.21 
Terminal: /dev/pts/0 
CPU: Samsung Exynos (Flattened Device Tree) (8) @ 1.300GHz 
Memory: 308MiB / 1988MiB 
```

**Comment by SaptakS** [comment]
A new release 2.6.1 is on the way and will be released no later than end of February. The new release should have this issue fixed.
