### ISSUE TITLE
Make Japanese as available language on documentation

### ISSUE THREAD

**Issue by luixxiul** [onionshare/onionshare#1884]
Since documentation has been translated into Japanese completely, fixing a bunch of strings wrongly translated as well, I would like to ask the team to add Japanese as available language by adding it on https://github.com/onionshare/onionshare/blob/main/docs/build.sh#L6, https://github.com/onionshare/onionshare/commit/1e3ec0d860090e0ba9ca1b78c43ac6e8cbec019e#diff-008dcb3426febd767787b1521f1fe33086313b927ea37eaab86df5fa88a51698R15, etc.

**Comment by SaptakS** [comment]
Thanks for pointing this out. I will do the needful.

**Comment by luixxiul** [comment]
It has been available on https://docs.onionshare.org/2.6.2/ja/ already, thanks.
