### ISSUE TITLE
Flatpak version: "No module named 'PySide2"

### ISSUE THREAD

**Issue by Rathmox** [onionshare/onionshare#1888]
I'm trying to run Onionshare flatpak version, but it crashes with the error:
`No module named 'PySide2`
does that mean a library is missing in the flatpak ?

**Comment by mikson022** [comment]
I have the same issues. Any way to resolve this?
```
$ flatpak run org.onionshare.OnionShare

Traceback (most recent call last):
  File "/app/bin/onionshare", line 5, in <module>
    from onionshare import main
  File "/app/lib/python3.10/site-packages/onionshare/__init__.py", line 29, in <module>
    from PySide2 import QtCore, QtWidgets, QtGui
ModuleNotFoundError: No module named 'PySide2'
```

**Comment by SaptakS** [comment]
Can you tell me which version of OnionShare do you have?

**Comment by mikson022** [comment]
I am running Fedora39. I installed it through the software store. 

Version 2.6 - 1 year ago

**Comment by SaptakS** [comment]
Can you please try updating to OnionShare 2.6.1 and check if you are still getting this error since we have updated the dependencies to use PySide6 now?

**Comment by SaptakS** [comment]
I think the upstream flathub version should be fixed by https://github.com/flathub/org.onionshare.OnionShare/pull/15

**Comment by Rathmox** [comment]
I confirm this patch fixes the issue

**Comment by SaptakS** [comment]
This should be resolved in flathub now. Closing this issue. Please feel free to reopen if this issue still occurs.
