### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by kerlann777** [onionshare/onionshare#1916]
the link never work and isn't https
don't work for anything

**Comment by SaptakS** [comment]
Can you please elaborate on the issue you are facing?

**Comment by thechoppinghand** [comment]
Appreciate your response! 

I didn't realize the link was no longer running that was my fault. I just checked.

Also - for future reference: You say "i hope this isn't the case" for my knowledge. If I want to send something to a friend they would need the Tor Browser as well right? What are the issues loading the link in a Firefox Browser or something like that. Does it just block the link ?

On the encryption - I see that thank you for clarifying for me.

**Comment by thechoppinghand** [comment]
@mig5 
Appreciate your response! 

I didn't realize the link was no longer running that was my fault. I just checked.

Also - for future reference: You say "i hope this isn't the case" for my knowledge. If I want to send something to a friend they would need the Tor Browser as well right? What are the issues loading the link in a Firefox Browser or something like that.

On the encryption - I see that thank you for clarifying for me.

**Comment by SaptakS** [comment]
> If I want to send something to a friend they would need the Tor Browser as well right? What are the issues loading the link in a Firefox Browser or something like that.

@thechoppinghand `.onion` links are different from regular links, so they can only be opened in browsers that support the Onion Protocol, for example Tor Browser. Firefox and many other commonly used browsers don't support `.onion` links and hence you will get an error if trying to open a `.onion` link in them.

**Comment by thechoppinghand** [comment]
@SaptakS thank you so much for clarifying.

**Comment by kerlann777** [comment]
i  try to open it with brave , but brave in a new window with tor.... you know that , so at this moment that not work
