### ISSUE TITLE
OnionShare For Android

### ISSUE THREAD

**Issue by ninja25538** [onionshare/onionshare#567]
I feel that having an onion share application would be very useful. Android already has Orbot to be able to launch hidden services and Android is made with Linux. Many people can't always access a computer or laptop and need to send secure files on the go.

**Comment by mig5** [comment]
We were talking about this the other day and agree it would be cool. Though the effort, and the codebase itself, would have to be treated pretty much as an entirely separate project, so it's unlikely to happen very soon.

**Comment by ninja25538** [comment]
Thanks

**Comment by mydarkthawts** [comment]
Such a bummer. I'd love to help with such a project. For now hosting the hidden service then manual copy and paste of the file and the URL will have to do lol

**Comment by trymeouteh** [comment]
Please create this on Android and iOS. This way people can share files on the go with others who are on the go weather they have a Android phone or iPhone.

If a Android comes about, please add it on F-Droid! F-Droid is the privacy minded app store.

**Comment by moonchitta** [comment]
Hi this is moonchitta here, developer of Coatex application. I am thinking about creating the onionshare flavour for Android. As being home quarantined, this could be best utilization of the time. I just wanted to know that can I use the same name for the Android flavour or do I need to name it something else?

**Comment by xia0mi** [comment]
Works as a reminder.... Any updates about Android version?

**Comment by Tigermouthbear** [comment]
yo, I got a working onionshare chat service to run on Android using flutter. The app uses an onionshare C library I'm writing, and it could probably be ported to iOS too. I'm planning on working more on this, chat is the only service I have implemented right now.

**Comment by mig5** [comment]
Good news - we have teams actively working on Android and iOS versions of OnionShare as we speak (likely to have simplified functionality, eg just Share, maybe Receive modes - no Chat etc). No ETA yet though.

https://github.com/onionshare/onionshare-android
https://github.com/onionshare/onionshare-ios

**Comment by mig5** [comment]
OnionShare on Android is an official thing now (obviously very pared down compared to desktop, but it is legit)

https://play.google.com/store/apps/details?id=org.onionshare.android&hl=en_US
https://f-droid.org/packages/org.onionshare.android.fdroid/
