### ISSUE TITLE
Fetch bridges for the user

### ISSUE THREAD

**Issue by Baccount** [onionshare/onionshare#661]
TorProject just added a feature into tor launcher.
```
to allow automated retrieval of bridges using Moat, a BridgeDB service which works
over a meek transport and requires the user to solve a CAPTCHA to
obtain bridges.
```
<img width="605" alt="bridge" src="https://user-images.githubusercontent.com/10781882/37009894-c9943c72-209d-11e8-8e8a-1c771b63dcb4.png">

**I wonder if this would be useful for onionshare, the ability to retrieve unblocked obfs4 bridges using meek. Large adversaries "China" may block the bundled obfs4 bridges.** 
https://gitweb.torproject.org/tor-launcher.git/commit/?id=e921bb15681ac54c9e937b564d31a2a6ec2ceb33
@mig5

**Comment by Baccount** [comment]
You can test the auto bridge feature in the latest Torbrowser nightly https://nightlies.tbb.torproject.org/tor-browser-builds/2018-03-04/nightly-osx-x86_64/TorBrowser-tbb-nightly-osx64_en-US.dmg

**Comment by micahflee** [comment]
This is complete now.
